stages:
  - test
  - build
variables:
  GIT_DEPTH: "3"
  SIMPLECOV: "true"
  RUST_BACKTRACE: "1"
  RUSTFLAGS: ""
  CARGOFLAGS: ""
cache:
  untracked: true
linux-test:
  stage: test
  image: node:8
  only:
    - beta
    - tags
    - stable
    - triggers
    - master
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash 
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn install
    - yarn test
  tags:
    - javascript
linux-build:
  stage: build
  image: node:8
  only:
    - beta
    - tags
    - stable
    - triggers
    - master
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash 
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn install
    - yarn build
    - yarn release --linux 
  tags:
    - javascript
osx-build:
  stage: build
  only:
    - beta
    - tags
    - stable
    - triggers
    - master
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash 
    - export PATH=$HOME/.yarn/bin:$PATH
    - brew install node
    - yarn install
    - yarn build
    - yarn release --mac
  tags:
    - osx 
