cache: yarn
install:
  - yarn install
  - lerna bootstrap
language: node_js
node_js:
  - "10"
script:
  - yarn lint
  - yarn test
  - yarn build
deploy:
  provider: script
  script:
    - yarn package --release
  on:
    branch: master
